import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
import xgboost as xgb # Will use XGBRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score # Updated metrics for regression
import numpy as np
import mlflow
import joblib
import os

# Load preprocessed data from CSVs generated by prep.py
Xtrain = pd.read_csv("sales_project/model_building/Xtrain.csv")
Xtest = pd.read_csv("sales_project/model_building/Xtest.csv")
ytrain = pd.read_csv("sales_project/model_building/ytrain.csv").squeeze()
ytest = pd.read_csv("sales_project/model_building/ytest.csv").squeeze()

print("Preprocessed train/test splits loaded successfully.")

# Define feature lists based on the features created/kept in prep.py
numeric_features = [
  "Product_Weight",
  "Product_Allocated_Area",
  "Product_MRP",
  "Store_Age",
  "Store_Product_Count",
  "Price_Per_Weight",
  "Relative_MRP",
  "Sales_Per_Area_Ratio",
  "Product_Sugar_Content_Mapped" # Now numerical
]
categorical_features = [
   "Product_Category",           # New categorical feature
   "Product_Type",
   "Store_Size",
   "Store_Location_City_Type",
   "Store_Type"
]

# Ensure that Xtrain and Xtest only contain the features specified in our lists
final_features = numeric_features + categorical_features
Xtrain = Xtrain[final_features]
Xtest = Xtest[final_features]

# Define the preprocessing steps
preprocessor = make_column_transformer(
    (StandardScaler(), numeric_features),
    (OneHotEncoder(handle_unknown="ignore"), categorical_features)
)

# Define base XGBoost model - changed to Regressor for sales forecasting
xgb_model = xgb.XGBRegressor(random_state=42)

# Define hyperparameter grid for XGBRegressor (reduced for faster execution)
param_grid = {
    'xgbregressor__n_estimators': [100, 150],
    'xgbregressor__max_depth': [3, 4],
    'xgbregressor__colsample_bytree': [0.5, 0.6],
    'xgbregressor__subsample': [0.8, 1.0],
    'xgbregressor__learning_rate': [0.05, 0.1],
    'xgbregressor__reg_lambda': [0.5, 0.6],
}

# Model pipeline
model_pipeline = make_pipeline(preprocessor, xgb_model)

# Set MLflow tracking URI to a local directory for CI/CD context
# In a real CI/CD setup, this would point to a remote MLflow server
mlflow_local_dir = "./mlruns_ci_cd"
os.makedirs(mlflow_local_dir, exist_ok=True)
mlflow.set_tracking_uri(f"file://{os.path.abspath(mlflow_local_dir)}")
mlflow.set_experiment("Sales-Prediction-Experiment-CI-CD")

with mlflow.start_run():
    # Hyperparameter tuning
    grid_search = GridSearchCV(model_pipeline, param_grid, cv=3, n_jobs=-1, scoring='neg_mean_squared_error') # Scoring for regression, reduced CV folds
    grid_search.fit(Xtrain, ytrain)

    # Log all parameter combinations and their mean test scores
    results = grid_search.cv_results_
    for i in range(len(results["params"])):
        param_set = results["params"][i]
        mean_score_neg_mse = results["mean_test_score"][i]
        std_score_neg_mse = results["std_test_score"][i]

        # Convert negative MSE to RMSE
        mean_rmse = np.sqrt(-mean_score_neg_mse)
        # Note: std of neg_mse is not directly std of rmse

        # Log each combination as a separate MLflow run
        with mlflow.start_run(nested=True):
            mlflow.log_params(param_set)
            mlflow.log_metric("mean_test_rmse", mean_rmse)

    # Log best parameters separately in main run
    mlflow.log_params(grid_search.best_params_)

    # Store and evaluate the best model
    best_model = grid_search.best_estimator_

    # Predict using the best model
    y_pred_train = best_model.predict(Xtrain)
    y_pred_test = best_model.predict(Xtest)

    # Calculate regression metrics
    rmse_train = np.sqrt(mean_squared_error(ytrain, y_pred_train))
    r2_train = r2_score(ytrain, y_pred_train)
    rmse_test = np.sqrt(mean_squared_error(ytest, y_pred_test))
    r2_test = r2_score(ytest, y_pred_test)

    mlflow.log_metrics({
        "train_rmse": rmse_train,
        "train_r2_score": r2_train,
        "test_rmse": rmse_test,
        "test_r2_score": r2_test
    })

    print(f"Train RMSE: {rmse_train:.2f}, Train R2: {r2_train:.2f}")
    print(f"Test RMSE: {rmse_test:.2f}, Test R2: {r2_test:.2f}")

    # Save the best model pipeline for deployment
    deployment_dir = "sales_project/deployment"
    os.makedirs(deployment_dir, exist_ok=True) # Ensure directory exists
    joblib.dump(best_model, os.path.join(deployment_dir, "best_model.pkl"))
    print(f"Best model pipeline saved to {os.path.join(deployment_dir, 'best_model.pkl')}")

    # Also log the model to MLflow
    mlflow.sklearn.log_model(best_model, "model")
